---
- name: simple-provisionig
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    aws_region: ap-northeast-1
    vpc_name: BTC-VPC
    vpc_cidr_block: 10.210.0.0/16
    subunet_cidr_block: 10.210.1.0/24
    instance_image: ami-06098fd00463352b6
    ec2_key_name: btc-class2
    instance_type: t2.micro    
  tasks:  
  - name: create a VPC
    ec2_vpc_net:
      name: "{{ vpc_name }}"
      cidr_block: "{{ vpc_cidr_block }}"
      region: "{{ aws_region }}"
      tags:
        Name: Test-VPC
      tenancy: default
    register: result_vpc
    
  - name: Create subnet
    ec2_vpc_subnet:
      state: present
      region: "{{ aws_region }}"
      vpc_id: "{{ result_vpc.vpc.id }}"
      cidr: "{{ subunet_cidr_block }}"
      tags:
        Name: webserver Subnet
    register: result_subnet
    
  - name: Create igw
    ec2_vpc_igw:
      region: "{{ aws_region }}"
      vpc_id: "{{ result_vpc.vpc.id }}"
      state: present
    register: result_igw
    
  - name: Set up public subnet route table
    ec2_vpc_route_table:
      vpc_id: "{{ result_vpc.vpc.id }}"
      region: "{{ aws_region }}"
      tags:
        Name: Public
      subnets:
        - "{{ result_subnet.subnet.id }}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{ result_igw.gateway_id }}"
    register: result_route_table
    
  - name: example using security group rule descriptions
    ec2_group:
      name: allow-tcp
      description: sg with rule descriptions
      vpc_id: "{{ result_vpc.vpc.id }}"
      #profile: "{{ aws_profile }}"
      region: "{{ aws_region }}"
      rules:
        - proto: tcp
          ports:
          - 80
          - 22
          cidr_ip: 0.0.0.0/0
          rule_desc: allow all on port 80
          
  - name: Create EC2
  ec2:
    key_name: "{{ ec2_key_name }}"
    instance_type: "{{ instance_type }}"
    image: "{{ instance_image }}"
    wait: np
    group: allow-tcp
    count: 1
    region: "{{ aws_region }}"
    vpc_subnet_id: "{{ result_subnet.subnet.id }}"
    assign_public_ip: yes
    instance_tags:
      Name: webserver
