---
- name: simple-provisionig
  hosts: localhost
  connection: localhost
  gather_facts: false
  vars:
    aws_region: ap-northeast-1
    vpc_name: BTC-VPC
    vpc_cidr_block: 10.210.0.0/16
    subunet_cidr_block: 10.210.1.0/24
    instance_image: ami-06098fd00463352b6
    ec2_key_name: btc-class2
    instance_type: t2.micro    
  tasks:  
  - name: create a VPC
    ec2_vpc_net:
      name: "{{ vpc_name }}"
      cidr_block: "{{ vpc_cidr_block }}"
      region: "{{ aws_region }}"
      tags:
        Name: Test-VPC
      tenancy: default
    register: result_vpc
    
  - name: Create subnet
    ec2_vpc_subnet:
      state: present
      region: "{{ aws_region }}"
      vpc_id: "{{ result_vpc.vpc.id }}"
      cidr: "{{ subunet_cidr_block }}"
      tags:
        Name: webserver Subnet
    register: result_subnet